[package]
name = "csvmanipulator"
version = "0.1.0"
authors = ["danieldeankon <daniel.d.k.1994@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.3"
